version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-with-orm
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: meubanco
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
